from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from urllib.parse import urlsplit, urlunsplit

import psycopg


@dataclass(frozen=True)
class TableSpec:
    name: str
    ddl: str


@dataclass(frozen=True)
class IndexSpec:
    name: str
    ddl: str


TABLE_SPECS: tuple[TableSpec, ...] = (
    TableSpec(
        name="meta",
        ddl="""
        CREATE TABLE IF NOT EXISTS meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
        """,
    ),
    TableSpec(
        name="users",
        ddl="""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            display_name TEXT,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'member',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="sites",
        ddl="""
        CREATE TABLE IF NOT EXISTS sites (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            site_name TEXT NOT NULL UNIQUE,
            site_code TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="user_site_permissions",
        ddl="""
        CREATE TABLE IF NOT EXISTS user_site_permissions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            site_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (user_id, site_id)
        )
        """,
    ),
    TableSpec(
        name="vendor_accounts",
        ddl="""
        CREATE TABLE IF NOT EXISTS vendor_accounts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            vendor_name TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="sheets",
        ddl="""
        CREATE TABLE IF NOT EXISTS sheets (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 1,
            site_id INTEGER,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="tasks",
        ddl="""
        CREATE TABLE IF NOT EXISTS tasks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sheet_id INTEGER,
            col_index INTEGER NOT NULL UNIQUE,
            vendor TEXT,
            location TEXT,
            name TEXT NOT NULL
        )
        """,
    ),
    TableSpec(
        name="floors",
        ddl="""
        CREATE TABLE IF NOT EXISTS floors (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sheet_id INTEGER,
            sort_order INTEGER NOT NULL UNIQUE,
            name TEXT NOT NULL,
            block_name TEXT,
            unit_count INTEGER NOT NULL
        )
        """,
    ),
    TableSpec(
        name="units",
        ddl="""
        CREATE TABLE IF NOT EXISTS units (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            floor_id INTEGER NOT NULL,
            sort_order INTEGER NOT NULL,
            name TEXT NOT NULL
        )
        """,
    ),
    TableSpec(
        name="progress",
        ddl="""
        CREATE TABLE IF NOT EXISTS progress (
            unit_id INTEGER NOT NULL,
            task_id INTEGER NOT NULL,
            value TEXT NOT NULL DEFAULT 'X',
            updated_by INTEGER,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (unit_id, task_id)
        )
        """,
    ),
    TableSpec(
        name="unit_extra",
        ddl="""
        CREATE TABLE IF NOT EXISTS unit_extra (
            unit_id INTEGER PRIMARY KEY,
            initial_check TEXT NOT NULL DEFAULT '',
            recheck_1 TEXT NOT NULL DEFAULT '',
            recheck_2 TEXT NOT NULL DEFAULT '',
            handover TEXT NOT NULL DEFAULT 'X',
            updated_by INTEGER,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="extra_fields",
        ddl="""
        CREATE TABLE IF NOT EXISTS extra_fields (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sheet_id INTEGER NOT NULL,
            field_key TEXT NOT NULL,
            name TEXT NOT NULL,
            field_type TEXT NOT NULL DEFAULT 'date',
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_builtin INTEGER NOT NULL DEFAULT 0,
            active INTEGER NOT NULL DEFAULT 1,
            UNIQUE (sheet_id, field_key)
        )
        """,
    ),
    TableSpec(
        name="unit_extra_values",
        ddl="""
        CREATE TABLE IF NOT EXISTS unit_extra_values (
            unit_id INTEGER NOT NULL,
            field_key TEXT NOT NULL,
            value TEXT NOT NULL DEFAULT '',
            updated_by INTEGER,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (unit_id, field_key)
        )
        """,
    ),
    TableSpec(
        name="vendor_contacts",
        ddl="""
        CREATE TABLE IF NOT EXISTS vendor_contacts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sheet_id INTEGER NOT NULL,
            vendor_name TEXT NOT NULL,
            contact_name TEXT NOT NULL DEFAULT '',
            contact_title TEXT NOT NULL DEFAULT '',
            contact_phone TEXT NOT NULL DEFAULT '',
            is_primary INTEGER NOT NULL DEFAULT 0,
            contact_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
    TableSpec(
        name="vendor_work_entries",
        ddl="""
        CREATE TABLE IF NOT EXISTS vendor_work_entries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sheet_id INTEGER NOT NULL,
            vendor_name TEXT NOT NULL,
            business_date TEXT NOT NULL,
            planned_at TEXT NOT NULL DEFAULT '',
            planned_headcount INTEGER NOT NULL DEFAULT 0,
            actual_headcount INTEGER NOT NULL DEFAULT 0,
            work_content TEXT NOT NULL DEFAULT '',
            work_headcount INTEGER NOT NULL DEFAULT 0,
            entry_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ),
)


INDEX_SPECS: tuple[IndexSpec, ...] = (
    IndexSpec(
        name="idx_user_site_permissions_user_id",
        ddl="CREATE INDEX IF NOT EXISTS idx_user_site_permissions_user_id ON user_site_permissions (user_id)",
    ),
    IndexSpec(
        name="idx_user_site_permissions_site_id",
        ddl="CREATE INDEX IF NOT EXISTS idx_user_site_permissions_site_id ON user_site_permissions (site_id)",
    ),
    IndexSpec(
        name="idx_vendor_accounts_vendor_name",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_accounts_vendor_name ON vendor_accounts (vendor_name)",
    ),
    IndexSpec(
        name="idx_sheets_site_id",
        ddl="CREATE INDEX IF NOT EXISTS idx_sheets_site_id ON sheets (site_id)",
    ),
    IndexSpec(
        name="idx_vendor_contacts_sheet_id",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_contacts_sheet_id ON vendor_contacts (sheet_id)",
    ),
    IndexSpec(
        name="idx_vendor_contacts_sheet_vendor",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_contacts_sheet_vendor ON vendor_contacts (sheet_id, vendor_name)",
    ),
    IndexSpec(
        name="idx_vendor_contacts_sheet_vendor_order",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_contacts_sheet_vendor_order ON vendor_contacts (sheet_id, vendor_name, contact_order)",
    ),
    IndexSpec(
        name="idx_vendor_work_entries_sheet_business_date",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_work_entries_sheet_business_date ON vendor_work_entries (sheet_id, business_date)",
    ),
    IndexSpec(
        name="idx_vendor_work_entries_sheet_vendor_date",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_work_entries_sheet_vendor_date ON vendor_work_entries (sheet_id, vendor_name, business_date)",
    ),
    IndexSpec(
        name="idx_vendor_work_entries_business_date",
        ddl="CREATE INDEX IF NOT EXISTS idx_vendor_work_entries_business_date ON vendor_work_entries (business_date)",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bootstrap staging PostgreSQL schema for release verification.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="Inspect target database and print planned schema changes.")
    mode.add_argument("--apply", action="store_true", help="Create missing staging schema objects.")
    return parser.parse_args()


def env_flag(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in {"1", "true", "yes", "on"}


def require_staging_guard() -> None:
    app_env = os.environ.get("APP_ENV", "").strip().lower()
    if app_env == "staging" or env_flag("STAGING_SCHEMA_BOOTSTRAP_ALLOWED"):
        return
    raise SystemExit(
        "Refusing to run schema bootstrap outside staging guard. "
        "Set APP_ENV=staging or STAGING_SCHEMA_BOOTSTRAP_ALLOWED=true."
    )


def require_postgres_database_url() -> str:
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        raise SystemExit("DATABASE_URL is required.")
    scheme = urlsplit(database_url).scheme.lower()
    if scheme not in {"postgresql", "postgres", "postgresql+psycopg"}:
        raise SystemExit(f"DATABASE_URL must point to PostgreSQL, got scheme '{scheme or 'missing'}'.")
    return database_url


def require_staging_target(database_url: str) -> None:
    parts = urlsplit(database_url)
    target_blob = " ".join(
        part
        for part in (
            parts.hostname or "",
            parts.path or "",
            parts.username or "",
            parts.netloc or "",
        )
        if part
    ).lower()
    if "staging" not in target_blob:
        raise SystemExit("Refusing to run because DATABASE_URL does not look like a staging target.")


def redact_database_url(database_url: str) -> str:
    parts = urlsplit(database_url)
    hostname = parts.hostname or ""
    if parts.port:
        hostname = f"{hostname}:{parts.port}"
    if parts.username:
        netloc = f"{parts.username}:***@{hostname}"
    else:
        netloc = hostname
    return urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))


def fetch_existing_tables(conn: psycopg.Connection) -> set[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
            ORDER BY table_name
            """
        )
        return {row[0] for row in cur.fetchall()}


def fetch_existing_indexes(conn: psycopg.Connection) -> set[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT indexname
            FROM pg_indexes
            WHERE schemaname = 'public'
            ORDER BY indexname
            """
        )
        return {row[0] for row in cur.fetchall()}


def print_summary_block(label: str, names: list[str]) -> None:
    print(f"{label}_count: {len(names)}")
    if names:
        print(f"{label}: {', '.join(names)}")
    else:
        print(f"{label}: <none>")


def main() -> int:
    args = parse_args()
    require_staging_guard()
    database_url = require_postgres_database_url()
    require_staging_target(database_url)

    mode = "apply" if args.apply else "dry-run"
    print("staging_schema_bootstrap_scope: postgres_only")
    print(f"target_database_url: {redact_database_url(database_url)}")
    print(f"mode: {mode}")
    print(f"app_env: {os.environ.get('APP_ENV', '').strip() or '<unset>'}")
    print(f"staging_schema_bootstrap_allowed: {str(env_flag('STAGING_SCHEMA_BOOTSTRAP_ALLOWED')).lower()}")
    print_summary_block("tables_planned", [spec.name for spec in TABLE_SPECS])
    print_summary_block("indexes_planned", [spec.name for spec in INDEX_SPECS])

    with psycopg.connect(database_url) as conn:
        before_tables = fetch_existing_tables(conn)
        before_indexes = fetch_existing_indexes(conn)

        planned_missing_tables = [spec.name for spec in TABLE_SPECS if spec.name not in before_tables]
        planned_missing_indexes = [spec.name for spec in INDEX_SPECS if spec.name not in before_indexes]

        print_summary_block("tables_existing_before", sorted(before_tables))
        print_summary_block("tables_missing_before", planned_missing_tables)
        print_summary_block("indexes_existing_before", sorted(before_indexes))
        print_summary_block("indexes_missing_before", planned_missing_indexes)

        if args.apply:
            with conn.cursor() as cur:
                for spec in TABLE_SPECS:
                    cur.execute(spec.ddl)
                for spec in INDEX_SPECS:
                    cur.execute(spec.ddl)
            conn.commit()
        else:
            conn.rollback()

        after_tables = fetch_existing_tables(conn)
        after_indexes = fetch_existing_indexes(conn)

        created_tables = [name for name in after_tables if name not in before_tables and name in {spec.name for spec in TABLE_SPECS}]
        created_indexes = [name for name in after_indexes if name not in before_indexes and name in {spec.name for spec in INDEX_SPECS}]
        missing_after_tables = [spec.name for spec in TABLE_SPECS if spec.name not in after_tables]
        missing_after_indexes = [spec.name for spec in INDEX_SPECS if spec.name not in after_indexes]

        print_summary_block("tables_existing_after", sorted(after_tables))
        print_summary_block("tables_created", sorted(created_tables))
        print_summary_block("tables_missing_after", missing_after_tables)
        print_summary_block("indexes_existing_after", sorted(after_indexes))
        print_summary_block("indexes_created", sorted(created_indexes))
        print_summary_block("indexes_missing_after", missing_after_indexes)

        if args.dry_run:
            print("PASS staging schema bootstrap dry-run passed.")
            return 0

        if missing_after_tables or missing_after_indexes:
            print("FAIL staging schema bootstrap failed.")
            return 1

    print("PASS staging schema bootstrap passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
